apiVersion: v1
kind: Namespace
metadata:
  name: dev-env
  [root@ip-10-1-1-211 kubernetes]# cat deployment.yml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: java-app-dep
      namespace: dev-env
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: java-app-pod
      template:
        metadata:
          labels:
            app: java-app-pod
        spec:
          imagePullSecrets:
            - name: artifactory-cred
          containers:
            - name: java-app-container
              image: emaad.jfrog.io/trend-java-pipeline-docker/api-loan-app:2.1.4
              imagePullPolicy: Always
              ports:
                - containerPort: 8000
              env:
                - name: CONSUMER_KEY
                  value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
                - name: CONSUMER_SECRET
                  value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
                - name: ACCESS_TOKEN
                  value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
                - name: ACCESS_TOKEN_SECRET
                  value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"




