apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
  namespace: dev-env
spec:
  type: NodePort
  selector:
    app: java-app-pod
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000
