---
- hosts: jenkins-master
  become: true
  tasks:
    - name: add jenkins key and repo
      yum_repository:
        name: jenkins
        description: adding jenkins repo
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: install java using amazon-linux-extras
      command: amazon-linux-extras install java-openjdk11 -y
      become: yes
      ignore_errors: yes

    - name: install jenkins
      yum:
        name: jenkins
        state: present

    - name: start jenkins service
      service:
        name: jenkins
        state: started


    - name: enable jenkins to start at boot time
      service:
        name: jenkins
        enabled: yes


        #add steps to install helm
        #add steps to install maven
        #add steps to install kubectl
        #add steps to install aws cli
        #add steps to install docker














